Taking a test will give this
program a basis for customizing individual lessons.  Don't
be concerned if you aren't typing as quickly as you can; you will
soon excel.  Everyone has
a quandary with number and symbol keys.  Don't expect to zoom through these
next sentences - just do your best!  "Her birthday
is 08/15/53."  Does 73% of $546.00 = $398.58?  Item #32 (jonquils) sold 2
units @
$76 & 1 @ $73.  *+* That's all folks! +*+

